---
name: Build and Deploy My Documents

on:
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, cancel in-progress runs to ensure only the latest commit is deployed, and avoid multiple deployments in case of several commits in a short time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    uses: fchastanet/my-documents/.github/workflows/build-site-action.yml@master
    with:
      site-name: 'my-documents'
    permissions:
      contents: read
      pages: write
      id-token: write
